name: portfolio_v3
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Articulat
      fonts:
        - asset: assets/fonts/ArticulatCF-Thin.otf
          weight: 100
        - asset: assets/fonts/ArticulatCF-Bold.otf
          weight: 700
        - asset: assets/fonts/ArticulatCF-DemiBold.otf
          weight: 600
        - asset: assets/fonts/ArticulatCF-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/ArticulatCF-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/ArticulatCF-Heavy.otf
          weight: 900
        - asset: assets/fonts/ArticulatCF-Light.otf
          weight: 300
        - asset: assets/fonts/ArticulatCF-Medium.otf
          weight: 500
        - asset: assets/fonts/ArticulatCF-Normal.otf
          weight: 400
        - asset: assets/fonts/ArticulatCF-Regular.otf
          weight: 400
    - family: HelveticaNow
      fonts:
        - asset: assets/fonts/HelveticaNowText-Black.ttf
        - asset: assets/fonts/HelveticaNowText-Bold.ttf
        - asset: assets/fonts/HelveticaNowText-ExtraBold.ttf
        - asset: assets/fonts/HelveticaNowText-ExtraLight.ttf
        - asset: assets/fonts/HelveticaNowText-Light.ttf
        - asset: assets/fonts/HelveticaNowText-Medium.ttf
        - asset: assets/fonts/HelveticaNowText-Regular.ttf
        - asset: assets/fonts/HelveticaNowText-Thin.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica-neue/LightEx.otf
        - asset: assets/fonts/helvetica-neue/UltraLightEx.otf
        - asset: assets/fonts/helvetica-neue/ThinEx.otf
        - asset: assets/fonts/helvetica-neue/RegularEx.otf

    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair-display/Bold.ttf
        - asset: assets/fonts/playfair-display/Regular.ttf
        - asset: assets/fonts/playfair-display/ExtraBold.ttf
        - asset: assets/fonts/playfair-display/Black.ttf
        - asset: assets/fonts/playfair-display/Medium.ttf
        - asset: assets/fonts/playfair-display/SemiBold.ttf

    - family: LensGrotesk
      fonts:
        - asset: assets/fonts/lens-grotesk/Bold.ttf
        - asset: assets/fonts/lens-grotesk/Book.ttf
        - asset: assets/fonts/lens-grotesk/ExtraLight.ttf
        - asset: assets/fonts/lens-grotesk/Light.ttf
        - asset: assets/fonts/lens-grotesk/Medium.ttf
        - asset: assets/fonts/lens-grotesk/Regular.ttf
        - asset: assets/fonts/lens-grotesk/SemiBold.ttf
        - asset: assets/fonts/lens-grotesk/Bold.ttf

    - family: Druk
      fonts:
        - asset: assets/fonts/druk-medium.otf

    - family: EditorialNew
      fonts:
        - asset: assets/fonts/EditorialNew-Regular.otf
          weight: 400
        - asset: assets/fonts/EditorialNew-Ultralight.otf
          weight: 200
